### ISSUE TITLE
how feature complete is this?

### ISSUE THREAD

**Issue by Merith-TK** [NewLunarFire/lua-3ds#1]
Like does it have access to ALL of lua 5.3.5? or is it limited?

I understand limits such as no `.so` plugins for the runtime but like... if I make an plain ass script in lua on my PC, and it works on my PC, will I be able to expect it to work (with minimal tweaking) on the 3ds?

**Comment by NewLunarFire** [comment]
Yes it has access to all of lua 5.3.5. I haven't tested all of the standard library but I don't expect much changes to be required. If there are incompatibilties it probably will be in the os module. os.time I had to modify because it didn't work out of the box, and I don't think I kept the same semantics: It returns time as if epoch was the moment you started the app (as opposed to January 1970).

**Comment by Merith-TK** [comment]
I am having an issue compiling however
```
$ make
FIND: Parameter format not correct
FIND: Parameter format not correct
linking lua-3ds.elf
arm-none-eabi-gcc: fatal error: cannot read spec file '3dsx.specs': No such file or directory
compilation terminated.
make[1]: *** [D:/Workspace/lua-3ds/lua-3ds.elf] Error 1
make: *** [all] Error 2
```

**Comment by NewLunarFire** [comment]
That looks more like an issue with your toolchain than the project itself. Are you sure you installed devkitarm properly with the 3ds developpement files?

**Comment by Merith-TK** [comment]
Found the issue and turns out I was using a old version of make that wasnt compatible with the project
